name: Dependabot auto-approve
on: pull_request
permissions:
  pull-requests: write
  contents: write
jobs:
  dependabot:
    runs-on: ubuntu-latest
    # Checking the author will prevent your Action run failing on non-Dependabot PRs
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'Zeichen-gegen-Mobbing/Projectcoordinator'
    steps:
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@21025c705c08248db411dc16f3619e6b5f9ea21a
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --squash "${{github.event.pull_request.html_url}}"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
