name: "Build and Deploy"
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: prd
    permissions: 
        id-token: write
        pull-requests: write
    steps:
      - uses: actions/checkout@v6
      - name: Prepare OpenTofu
        uses: ./.github/actions/infra_preparation
        with:
          client-id: "${{ vars.AZURE_CLIENT_ID }}"
          tenant-id: "${{ vars.AZURE_TENANT_ID }}"
          subscription-id: "${{ vars.AZURE_SUBSCRIPTION_ID }}"
      - name: terraform output
        id: tfoutputs
        uses: dflook/terraform-output@v2
        with:
          path: infrastructure
          backend_config: |
            resource_group_name=${{ vars.BACKEND_AZURE_RESOURCE_GROUP_NAME }}
            storage_account_name=${{ vars.BACKEND_AZURE_STORAGE_ACCOUNT_NAME }}
            container_name=${{ vars.BACKEND_AZURE_STORAGE_ACCOUNT_CONTAINER_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ steps.tfoutputs.outputs.static_web_app_api_key }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "src/FrontEnd" # App source code path
          api_location: "src/api" # Api source code path - optional
          output_location: "wwwroot" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
